# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [ ]:
'''
Ans: list(a) for 2維 ndarray 會轉換成 1維的list ，但是元素還是 array
     a.tolist() 將 2維的 ndarray 轉換成 2維的list，元素是數字
'''

'\nYour Code\n'

### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [8]:
import numpy as np
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
print('-------------------------a =',a)
print('type(a)=',type(a))  # type(a)= <class 'numpy.ndarray'>
print('a.ndim=',a.ndim)    # 陣列有多少維度
print('a.shape=',a.shape)  # 每個維度的大小
print('a.size=',a.size)    # 陣列當中有幾個元素
print('a.dtype=',a.dtype)  #  陣列中的資料型態
print('a.itemsize=',a.itemsize)  # 陣列中每個元素佔用的空間
print('a.data=',a.data)    # 陣列所存在的記憶體位置

print('-------------------------b =\n',b)
print('type(b)=',type(b))  # type(a)= <class 'numpy.ndarray'>
print('b.ndim=',b.ndim)    # 陣列有多少維度
print('b.shape=',b.shape)  # 每個維度的大小
print('b.size=',b.size)    # 陣列當中有幾個元素
print('b.dtype=',b.dtype)  #  陣列中的資料型態
print('b.itemsize=',b.itemsize)  # 陣列中每個元素佔用的空間
print('b.data=',b.data)    # 陣列所存在的記憶體位置

print('-------------------------c =\n',c)
print('type(c)=',type(c))  # type(a)= <class 'numpy.ndarray'>
print('c.ndim=',c.ndim)    # 陣列有多少維度
print('c.shape=',c.shape)  # 每個維度的大小
print('c.size=',c.size)    # 陣列當中有幾個元素
print('c.dtype=',c.dtype)  #  陣列中的資料型態
print('c.itemsize=',c.itemsize)  # 陣列中每個元素佔用的空間
print('c.data=',c.data)    # 陣列所存在的記憶體位置

-------------------------a = [9 4 8 8 8 7]
type(a)= <class 'numpy.ndarray'>
a.ndim= 1
a.shape= (6,)
a.size= 6
a.dtype= int32
a.itemsize= 4
a.data= <memory at 0x000001CEE4424640>
-------------------------b =
 [[4 0 1 0]
 [6 9 0 4]
 [2 8 1 4]]
type(b)= <class 'numpy.ndarray'>
b.ndim= 2
b.shape= (3, 4)
b.size= 12
b.dtype= int32
b.itemsize= 4
b.data= <memory at 0x000001CEE44446C0>
-------------------------c =
 [[[8 8]
  [9 7]
  [4 4]]

 [[0 1]
  [0 1]
  [3 7]]]
type(c)= <class 'numpy.ndarray'>
c.ndim= 3
c.shape= (2, 3, 2)
c.size= 12
c.dtype= int32
c.itemsize= 4
c.data= <memory at 0x000001CEE44A5B80>


In [ ]:

a = np.random.randint(10, size=6) 

'''
Your Code
'''

[1 1 2 0 1 6]
1
(6,)
6
int64
8
6
<class 'numpy.ndarray'>


In [ ]:
b = np.random.randint(10, size=(3,4)) 

'''
Your Code
'''

[[0 7 9 3]
 [8 2 7 7]
 [9 3 3 3]]
2
(3, 4)
12
int64
8
3
<class 'numpy.ndarray'>


In [ ]:
c = np.random.randint(10, size=(2,3,2)) 

'''
Your Code
'''

[[[1 3]
  [2 8]
  [2 5]]

 [[0 0]
  [8 0]
  [1 6]]]
3
(2, 3, 2)
12
int64
8
2
<class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [ ]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[7, 6, 7, 3, 7, 5]
[7, 6, 7, 3, 7, 5]


In [ ]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[5, 7, 4, 6], [9, 4, 0, 1], [9, 1, 2, 9]]
[array([5, 7, 4, 6]), array([9, 4, 0, 1]), array([9, 1, 2, 9])]


In [ ]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[0, 4], [0, 1], [9, 5]], [[8, 7], [8, 2], [6, 0]]]
[array([[0, 4],
       [0, 1],
       [9, 5]]), array([[8, 7],
       [8, 2],
       [6, 0]])]


In [ ]:
def tolist(iterable):
    '''
    Your Code
    '''

print(tolist(a))
print(tolist(b))
print(tolist(c))

[7, 6, 7, 3, 7, 5]
[[5, 7, 4, 6], [9, 4, 0, 1], [9, 1, 2, 9]]
[[[0, 4], [0, 1], [9, 5]], [[8, 7], [8, 2], [6, 0]]]


[7, 6, 7, 3, 7, 5]
[[5, 7, 4, 6], [9, 4, 0, 1], [9, 1, 2, 9]]
[[[0, 4], [0, 1], [9, 5]], [[8, 7], [8, 2], [6, 0]]]
