# [作業目標]

1. 請比較對一個 100 x 100 * 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。

2. 如何從一個陣列中，找出出現頻率最高的數值與位置？

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. 請比較對一個 1000 x 100 x 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。




In [5]:
# 記得先 Import 正確的套件
import numpy as np

In [10]:
Z = np.random.randint(0, 10, 1000000).reshape(100, 100, 100)
print(Z)

[[[7 1 3 ... 2 2 8]
  [2 1 3 ... 3 7 4]
  [6 3 9 ... 5 2 6]
  ...
  [6 8 2 ... 7 6 2]
  [2 4 7 ... 5 7 3]
  [1 1 1 ... 5 5 2]]

 [[7 8 4 ... 3 5 4]
  [7 8 2 ... 5 7 9]
  [3 9 1 ... 6 7 6]
  ...
  [3 7 7 ... 7 3 6]
  [5 2 8 ... 0 7 0]
  [1 5 4 ... 1 2 9]]

 [[7 6 4 ... 4 5 7]
  [2 9 4 ... 7 2 5]
  [5 2 1 ... 0 2 0]
  ...
  [8 2 2 ... 5 5 0]
  [9 9 8 ... 1 3 2]
  [0 7 4 ... 3 0 7]]

 ...

 [[5 7 2 ... 0 4 1]
  [1 0 1 ... 2 6 9]
  [5 9 2 ... 2 6 1]
  ...
  [7 4 3 ... 6 1 3]
  [4 6 4 ... 2 6 7]
  [5 1 6 ... 6 4 7]]

 [[4 9 5 ... 8 0 1]
  [8 7 6 ... 9 1 0]
  [5 5 1 ... 6 9 8]
  ...
  [1 1 0 ... 1 2 4]
  [9 2 0 ... 5 8 2]
  [2 3 4 ... 3 9 6]]

 [[2 9 4 ... 5 7 3]
  [9 1 0 ... 6 5 3]
  [4 7 3 ... 7 2 4]
  ...
  [6 2 6 ... 3 8 7]
  [3 5 1 ... 7 1 5]
  [5 3 5 ... 1 8 1]]]


In [28]:
%timeit -n 10 a = 2
for indxe_x, a in enumerate(Z): 
    for indxe_y ,b in enumerate(a):
        for indxe_z, c in enumerate(b):
            Z[indxe_x,indxe_y,indxe_z] = Z[indxe_x,indxe_y,indxe_z]+1
# print(Z)

31.4 ns ± 8.33 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [73]:
%timeit -n 10 a = 2
for i in np.nditer(Z):
    i = i+1

30 ns ± 9.26 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [72]:
%timeit -n 10 a = 2
for i in Z.flat:
    i = i+1

57.1 ns ± 26 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [27]:
Z = np.random.randint(0, 10, 1000000).reshape(100, 100, 100)
%timeit -n 10 a = 2
# print(Z)
#print('-------------------------------------')
Z = Z+1
# print(Z)

35.7 ns ± 10.5 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [26]:
Z = np.random.randint(0, 10, 1000000).reshape(100, 100, 100)
print('Z[0]=\n',Z[0])
%timeit -n 10 a = 2
it = np.nditer(Z, flags = ['multi_index'])
while not it.finished:
    Z[it.multi_index]= Z[it.multi_index]+1
    it.iternext()
# print('Z[0]=\n',Z[0])


Z[0]=
 [[6 3 0 ... 9 7 4]
 [9 9 4 ... 8 7 3]
 [6 9 0 ... 2 3 5]
 ...
 [3 9 8 ... 8 9 9]
 [8 7 7 ... 6 7 7]
 [6 5 2 ... 0 5 4]]
32.9 ns ± 11.6 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


### 2. 如何從一個陣列中，找出出現頻率最高的數值與位置？


In [50]:
Z = np.random.randint(0,10,50)
print(Z)

[6 4 5 2 1 9 4 4 2 6 7 9 4 8 8 9 0 6 7 9 8 4 1 0 6 2 0 9 3 2 2 4 6 8 2 0 0
 6 7 3 9 6 6 3 5 5 9 5 3 8]


In [75]:
rint = (np.bincount(Z).argmax())
print(rint)
print('np.bincount(Z)=',np.bincount(Z))
print(np.where(Z == rint)[0])

6
np.bincount(Z)= [5 2 6 4 6 4 8 3 5 7]
[ 0  9 17 24 32 37 41 42]


In [76]:
hist,bins = np.histogram(Z) 
print(hist)
hightest= hist.argmax()
print('出現頻率最高的數值=',hightest)

[5 2 6 4 6 4 8 3 5 7]
出現頻率最高的數值= 6


In [77]:
list1 =[]
for index, a in enumerate(Z):
    if  a == hightest :
         list1.append(index)
print('出現頻率最高的數值的位置=',list1)

出現頻率最高的數值的位置= [0, 9, 17, 24, 32, 37, 41, 42]


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [79]:
a = np.random.randint(10, size=6) 
def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    return [tolist(obj) for obj in iterable]

print(tolist(a))
print(tolist(b))
print(tolist(c))

[9, 8, 0, 4, 0, 4]
[[5, 7, 2, 8], [0, 9, 1, 9], [0, 7, 8, 2]]
[[[5, 4], [8, 9], [7, 9]], [[5, 2], [8, 6], [0, 6]]]


In [71]:
a = np.random.randint(10, size=6) 
print('a=',a)
print('a.tolist()=',a.tolist())

list1=[]
for value in a:
    list1.append(value)
print('list1=',list1)
# print('-------------------------------------')
# it = np.nditer(b, flags = ['multi_index'])
# print('--------------------------------------')
# b = np.random.randint(10, size=(3,4)) 
# print('b=',b)
# list2=[]
# print('b.tolist()=\n',b.tolist())
# while not it.finished:
#     print(it.multi_index)
#     list2.append(it.multi_index) = b(it.multi_index)
#     np.append(a, [[1,2,3,4]], 0) 
#    # list1[it.multi_index[0],it.multi_index[1],it.multi_index[2]]=b[,it.multi_index] 
#    it.iternext()
# c = np.random.randint(10, size=(2,3,2)) 
# print('c.tolist()=\n',c.tolist())
# print('list(c)',list(c))


a= [4 5 1 0 2 2]
a.tolist()= [4, 5, 1, 0, 2, 2]
list1= [4, 5, 1, 0, 2, 2]


In [ ]:
'''
Your Code
'''