# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [3]:
A1:# np.zeros()函数返回一个元素全为0且给定形状和類型的數組
   # np.empty()創建的数组中，包含的均是無意義的數值
A2: 設計 np.zeros() 主要是運用在要給初值的情況
    設計 np.empty() 主要運用只要產生陣列元素，值沒有意義，是創建最快的方法

'\nYour Code\n'

### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [9]:
# '''
import numpy as np
a = np.random.randn(2, 3)*5
print("a =",a)
b = a.astype(np.int32) 
print("b =",b)
# '''

a = [[ 6.23425572 -3.27478812 -4.62494336]
 [ 1.95091293  2.01063021 -8.46379127]]
b = [[ 6 -3 -4]
 [ 1  2 -8]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [21]:
m = 20
n = 40
a = np.random.randn(2, 3)
print('a=',a)
print("------------------------")
# print(a)
for index_x,i in enumerate(a):
    print(i)
    for index_y, j in enumerate(i):
        a[index_x,index_y] =j*(n-m)+m
print('a=',a)
b = a.astype(np.int32) 
print('b=',b)

a= [[ 0.45569196 -0.2687894   1.54890024]
 [-0.02332403 -0.08703889  0.09484014]]
------------------------
[ 0.45569196 -0.2687894   1.54890024]
[-0.02332403 -0.08703889  0.09484014]
a= [[29.11383921 14.62421207 50.97800483]
 [19.53351939 18.25922211 21.89680276]]
b= [[29 14 50]
 [19 18 21]]
