# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [7]:
import numpy as np
a=np.arange(12).reshape(3,4)
print(a)
print(a.sum())    # 是呼叫numpy.array自身的sum()
print(np.sum(a))  # numpy的內建函式numpy.sum()  ,对numpy进行的特定操作。
print(sum(a))     # python sum函数, sum（） 对序列进行求和 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
66
66
[12 15 18 21]


### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [ ]:
# 記得先 Import 正確的套件
import numpy as np

In [9]:
A = np.random.random((5, 5))
print('A=\n',A)
print()
range = np.max(A)-np.min(A)
result = (A-np.min(A))/range
print('result=\n',result)

A=
 [[0.92633654 0.80515108 0.47612448 0.61898174 0.57871526]
 [0.81603332 0.95488019 0.22731284 0.80978529 0.42816637]
 [0.38413582 0.90733088 0.07552672 0.89748048 0.10754257]
 [0.03330166 0.61407533 0.60686073 0.30770258 0.98804712]
 [0.46729833 0.35592835 0.94101658 0.73755237 0.43944088]]

result=
 [[0.93536437 0.80843477 0.46381244 0.61344107 0.57126598]
 [0.81983281 0.96526098 0.20320723 0.81328863 0.41358113]
 [0.36746355 0.91545785 0.04422651 0.90514054 0.07775989]
 [0.         0.6083021  0.60074553 0.28740741 1.        ]
 [0.45456793 0.33791906 0.95074024 0.7376319  0.42539005]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [13]:
import numpy as np
A = np.random.randint(10,size=10)
print('A=',A)
A[np.argmax(A)] =-1
print('Result A=',A)

A= [5 5 3 7 1 0 4 1 5 8]
Result A= [ 5  5  3  7  1  0  4  1  5 -1]
