# [作業目標]

1. [簡答題] 請問 type(...) 跟 a.dtype 這兩個語法有什麼不同？

```
print('type(a): ', type(a))
print('a.dtype: ', a.dtype)
```

2. 請撰寫一個判斷 a 的元素是否等於指定資料型態的函式

3. [簡答題] 承上題，請判斷下列三種寫法為何不正確？

```
def is_dtype(a, t):
    return a.dtype is t

def is_dtype(a, t):
    return type(a) == np.dtype(t)

def is_dtype(a, t):
    return type(a) is np.dtype(t)
```

# 作業 

### 1. [簡答題] 請問 type(...) 跟 a.dtype 這兩個語法有什麼不同？

```
print('type(a): ', type(a))
print('a.dtype: ', a.dtype)
```


In [15]:
'\n 1. type() : 用於獲取引數資料型別 \n'
# ex
import numpy as np
a=[1,2,3]
print(type(a))
'\n 2. dtype : 用於獲取陣列中元素的型別 \n'
#ex
b = np.array(a)
print(b.dtype)
# Answer -----------------------------------
'''
 type(a) 是回傳 a 變數的型態；a.dtype 是回傳 a 陣列中的元素型態。
'''

<class 'list'>
int32


'\n type(a) 是回傳 a 變數的型態；a.dtype 是回傳 a 陣列中的元素型態。\n'

### 2. 請撰寫一個判斷 a 的元素是否等於指定資料型態的函式，並且通過測試。



In [11]:
# 記得先 Import 正確的套件

'''
Your Code
'''
import numpy as np
a= np.arange(15).reshape(3,5)
print('a=\n',a)
print(a.dtype == 'int32')
print(a.dtype is np.dtype('int32'))

a=
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
True
True


In [12]:
def is_dtype(a, t):
    '''
    Your Code
    '''
    return a.dtype is np.dtype(t) 

In [13]:
a = np.random.randint(10, size=6) 

# 測試一
print(is_dtype(a, 'int')) # True

# 測試二
print(is_dtype(a, np.int)) # True

# 測試三
print(is_dtype(a, np.dtype('int'))) # True

True
True
True


C:\Users\mikal\AppData\Local\Temp\ipykernel_21552\1406627198.py:7: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  print(is_dtype(a, np.int)) # True


### 3. [簡答題] 承上題，請判斷下列三種寫法為何不正確？

```
def is_dtype(a, t):
    return a.dtype is t

def is_dtype(a, t):
    return type(a) == np.dtype(t)

def is_dtype(a, t):
    return type(a) is np.dtype(t)
```

In [16]:
''' def is_dtype(a, t):
    return a.dtype is t ''' 
'''
type() 是檢查變數的型態，而不是元素的型態； is 相對 == 更嚴格，一定要型態正確才會回傳 True。
'''
# Ans: a.dtype is 陣列的型別， t 不是陣列的型別

'\ntype() 是檢查變數的型態，而不是元素的型態； is 相對 == 更嚴格，一定要型態正確才會回傳 True。\n'

In [ ]:
'''
def is_dtype(a, t):
    return type(a) == np.dtype(t) '''

'\n type() 是檢查變數的型態，而不是元素的型態； is 相對 == 更嚴格，一定要型態正確才會回傳 True。\n'
# Ans: type(a) is a 的型別，   np.dtype(t) 是陣列的型別

In [ ]:
'''def is_dtype(a, t):
      return type(a) is np.dtype(t)
```
# Ans: type(a) is a 的型別，   np.dtype(t) 是陣列的型別